### ISSUE TITLE
karmaRun if failing due to dependency error on windows

### ISSUE THREAD

**Issue by rpandit** [craigburke/karma-gradle#9]
Selected primary task 'karmaRun' from project :
Tasks to be executed: [task ':JavaScriptTesting:karmaInit', task ':JavaScriptTesting:nodeSetup', tas
k ':JavaScriptTesting:karmaDependencies', task ':JavaScriptTesting:karmaGenerateConfig', task ':Java
ScriptTesting:karmaRun']
:JavaScriptTesting:karmaInit (Thread[main,5,main]) started.
:JavaScriptTesting:karmaInit
Skipping task ':JavaScriptTesting:karmaInit' as it has no actions.
:JavaScriptTesting:karmaInit UP-TO-DATE
:JavaScriptTesting:karmaInit (Thread[main,5,main]) completed. Took 0.018 secs.
:JavaScriptTesting:nodeSetup (Thread[main,5,main]) started.
:JavaScriptTesting:nodeSetup
Skipping task ':JavaScriptTesting:nodeSetup' as it is up-to-date (took 0.007 secs).
:JavaScriptTesting:nodeSetup UP-TO-DATE
:JavaScriptTesting:nodeSetup (Thread[main,5,main]) completed. Took 0.019 secs.
:JavaScriptTesting:karmaDependencies (Thread[main,5,main]) started.
:JavaScriptTesting:karmaDependencies
Executing task ':JavaScriptTesting:karmaDependencies' (up-to-date check took 0.002 secs) due to:
  No history is available.
Starting process 'command 'cmd''. Working directory: C:\workspace\current\wm_rma\JavaScriptTesting C
ommand: cmd /c ""C:\Users\Administrator.gradle\nodejs\node-v4.2.3-windows-x64\bin\node.exe" "C:\Use
rs\Administrator.gradle\nodejs\node-v4.2.3-linux-x86\lib\node_modules\npm\bin\npm-cli.js" "install"
 "--silent" "karma" "karma-chrome-launcher" "karma-jasmine" "jasmine-core""
Successfully started process 'command 'cmd''
:JavaScriptTesting:karmaDependencies FAILED
:JavaScriptTesting:karmaDependencies (Thread[main,5,main]) completed. Took 1.185 secs.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':JavaScriptTesting:karmaDependencies'.
  > Process 'command 'cmd'' finished with non-zero exit value 1
  -----------------------------------------
  stacktrace:

:JavaScriptTesting:karmaDependencies FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':JavaScriptTesting:karmaDependencies'.
  
  > Process 'command 'cmd'' finished with non-zero exit value 1
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':JavaScriptTesting:karmaDepe
  ndencies'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Execute
  ActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActions
  TaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExe
  cutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTask
  Executer.java:64)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExec
  uter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmpt
  ySourceFilesTaskExecuter.java:42)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWit
  hNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExec
  uter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMo
  stOnceTaskExecuter.java:43)
      at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:
  306)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(Ab
  stractTaskPlanExecutor.java:79)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(Ab
  stractTaskPlanExecutor.java:63)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTa
  skPlanExecutor.java:51)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.ja
  va:23)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.
  java:88)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java
  :29)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
      at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:3
  2)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:
  149)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProces
  sBuildActionExecuter.java:80)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecute
  r.java:36)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecute
  r.java:26)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineA
  ctionFactory.java:237)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineA
  ctionFactory.java:210)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.j
  ava:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.j
  ava:24)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFac
  tory.java:206)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFac
  tory.java:169)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33
  )
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22
  )
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
      at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd'' finished with non-zero
  exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(Defaul
  tExecHandle.java:365)
      at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
      at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:151)
      at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:780)
      at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:776)
      at org.gradle.api.Project$exec$20.call(Unknown Source)
      at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:43)
      at com.moowork.gradle.node.exec.NodeExecRunner.doExecute(NodeExecRunner.groovy:44)
      at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:83)
      at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
      at com.moowork.gradle.node.exec.NpmExecRunner.doExecute(NpmExecRunner.groovy:37)
      at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:83)
      at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
      at com.moowork.gradle.node.task.NpmTask.exec(NpmTask.groovy:74)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskA
  ction.doExecute(AnnotationProcessingTaskFactory.java:218)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskA
  ction.execute(AnnotationProcessingTaskFactory.java:211)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskA
  ction.execute(AnnotationProcessingTaskFactory.java:200)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteA
  ctionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Execute
  ActionsTaskExecuter.java:61)
      ... 47 more

BUILD FAILED

Total time: 26.959 secs

C:\workspace\current>

**Comment by ralfhergert** [comment]
To get a better clue what's going wrong you may want to try:
`gradle karmaRun -PkarmaDebug=true`
The parameter karmaDebug controls whether or not node is called in silent mode.

In my case I could see that npm could not establish a network connection (due to missing proxy settings).

To fix the missing proxy configuration there are several options. Regarding to [https://github.com/nodejs/node/blob/d538811fc8b920f3f36d5f21a4c23e270367ceb0/deps/npm/doc/misc/npm-config.md](url) a config file `.npmrc` can be used or the enviroment variables `HTTP_PROXY` and `HTTPS_PROXY` can be set accordingly.
